on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        working-directory: ./backend

      - name: Run tests
        run: forge test -vvv
        working-directory: ./backend

      - name: Run snapshot
        run: forge snapshot
        working-directory: ./backend
  frontend:
    runs-on: ubuntu-latest
    name: Deploy front end
    steps:
      - uses: actions/checkout@v2
      - name: Deploy site using fleek
        id: deploy
        uses: fleekhq/action-deploy@v1
        with:
          apiKey: ${{ secrets.FLEEK_API_KEY }}
          workDir: frontend
      - name: Get the output url
        run: echo "Deploy url is ${{ steps.deploy.outputs.deployUrl }}"